# Generated by Django 5.2.10 on 2026-01-21 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='user_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='related_hobby',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('MUSIC', 'Music'), ('IDOL', 'Idol'), ('MOVIE', 'Movie'), ('DRAMA', 'Drama'), ('SPORTS', 'Sports (Team)'), ('MATCH', 'Match Schedule'), ('ACTOR', 'Actor'), ('EXHIBITION', 'Exhibitions & Shows'), ('FOOD', 'Food'), ('ETC', 'Etc')], default='ETC', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='poster_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Untitled', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
