# Generated by Django 5.2.10 on 2026-01-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_image_post_user_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('MUSIC', 'Music'), ('IDOL', 'Idol'), ('MOVIE', 'Movie'), ('DRAMA', 'Drama'), ('SPORTS', 'Sports (Team)'), ('MATCH', 'Match Schedule'), ('ACTOR', 'Actor'), ('SHOW', 'Exhibitions & Shows'), ('FOOD', 'Food'), ('ETC', 'Etc')], default='ETC', max_length=20),
        ),
    ]
