# Generated by Django 5.2.10 on 2026-01-16 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HobbyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MUSIC', '음악'), ('IDOL', '아이돌'), ('MOVIE', '영화'), ('DRAMA', '드라마'), ('OTT', 'OTT'), ('ACTOR', '배우'), ('SPORTS', '스포츠'), ('SHOW', '공연/전시'), ('FOOD', '음식')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('image_url', models.URLField(blank=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
