# Generated by Django 5.2.10 on 2026-01-17 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobbyitem',
            name='user',
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SPORTS', '스포츠 (팀/선수)'), ('MATCH', '경기 기록 (직관/집관)'), ('MUSIC', '음악'), ('IDOL', '아이돌'), ('MOVIE', '영화'), ('DRAMA', '드라마'), ('OTT', 'OTT'), ('ACTOR', '배우'), ('SHOW', '공연/전시'), ('FOOD', '음식'), ('ETC', '기타')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('date_experienced', models.DateField()),
                ('rating', models.FloatField(default=0.0)),
                ('content', models.TextField(blank=True)),
                ('home_team', models.CharField(blank=True, max_length=100, null=True)),
                ('away_team', models.CharField(blank=True, max_length=100, null=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('my_status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
