# Generated by Django 5.2.10 on 2026-01-17 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0002_remove_hobbyitem_user_post'),
        ('posts', '0002_post_likes_alter_post_related_hobby'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HobbyItem',
        ),
    ]
