# Generated by Django 5.2.10 on 2026-01-17 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0004_remove_post_rating_post_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_experienced',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('MUSIC', 'Music'), ('IDOL', 'Idol'), ('MOVIE', 'Movie'), ('DRAMA', 'Drama'), ('SPORTS', 'Sports (Team)'), ('MATCH', 'Match Schedule'), ('ACTOR', 'Actor'), ('EXHIBITION', 'Exhibitions & Shows'), ('FOOD', 'Food'), ('ETC', 'Etc')], max_length=20),
        ),
        migrations.CreateModel(
            name='HobbyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MUSIC', 'Music'), ('IDOL', 'Idol'), ('MOVIE', 'Movie'), ('DRAMA', 'Drama'), ('SPORTS', 'Sports (Team)'), ('MATCH', 'Match Schedule'), ('ACTOR', 'Actor'), ('EXHIBITION', 'Exhibitions & Shows'), ('FOOD', 'Food'), ('ETC', 'Etc')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('bio', models.CharField(blank=True, default='자신을 한 줄로 소개해 주세요.', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
