# Generated by Django 5.2.10 on 2026-01-21 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0005_rename_date_experienced_post_date_and_more'),
        ('posts', '0004_rename_image_post_user_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
