"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u-+jt%e5@6)-*qx=2a7iya&%#j#kileniq=i3q2&hrbk6sjzr2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework.authtoken',  # 토큰 기반 로그인을 위해 필수
    'dj_rest_auth',              # 로그인/로그아웃 API
    'django.contrib.sites',      # allauth가 사용하는 사이트 관리 기능
    'allauth',                   # 회원가입 관리
    'allauth.account',           # 계정 관리
    'allauth.socialaccount',     # 소셜 로그인 (나중을 위해 미리)
    'allauth.socialaccount.providers.google', # 구글 로그인 제공자
    'dj_rest_auth.registration', # 회원가입 API

    'hobbies',         # 취향 앱
    'posts',           # 기록 앱
    'users',           # 사용자 앱
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

AUTHENTICATION_BACKENDS = [
    # 1. Django 관리자 페이지 접속 등을 위한 기본 인증
    'django.contrib.auth.backends.ModelBackend',

    # 2. Allauth를 통한 이메일/소셜 로그인 인증 (필수!)
    'allauth.account.auth_backends.AuthenticationBackend',
]

# 3. 인증 설정
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication', # 토큰 방식
    ],
}

# 4. 구글 로그인 설정 (이건 맨 아래에 붙여넣으세요)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'madcamp_db',      # 방금 만든 DB 이름
        'USER': 'postgres',        # 설치할 때 정한 ID (보통 postgres)
        'PASSWORD': '5546',  # ★여기에 본인 비번 넣으세요!★
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SITE_ID = 1  # 사이트 식별 번호 (필수)

# 로그인 처리 방식 (이메일 필수 아님, username 필수 아님 등 편하게 설정)
SOCIALACCOUNT_ADAPTER = 'hobbies.adapters.CustomSocialAccountAdapter'

# ★ [수정] 이메일 연동을 위한 최적화 설정
ACCOUNT_EMAIL_REQUIRED = True        # 일반 가입도 이메일 필수 (그래야 구글이랑 비교함)
ACCOUNT_UNIQUE_EMAIL = True          # 이메일 중복 금지
ACCOUNT_USERNAME_REQUIRED = False    # 아이디는 필수가 아님 (이메일 위주)
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_EMAIL_VERIFICATION = 'none'  # 이메일 인증 메일 발송 안 함(개발용)
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

CORS_ALLOW_CREDENTIALS = True